@extends('layouts.app')
@section('content')
<header class="nav"><div class="brand"><div class="emblem">✦</div><div><strong>Public Grievance</strong><small>Complaint Portal</small></div></div><nav><a href="#home">Home</a><a href="#complaint">File Complaint</a><a href="{{ route('complaints.track') }}">Track Complaint</a><a href="#guidelines">Guidelines</a><a href="#faq">FAQs</a></nav><a class="navbtn" href="#complaint">File a Complaint →</a></header>
<main id="home"><section class="hero"><div class="hero-copy"><span class="eyebrow">PEOPLE · GOVERNANCE · PROGRESS</span><h1>Your Voice Builds a <span>Better India</span></h1><p>Report issues, share your concerns and help build a more transparent, responsive and developed India.</p><div class="trust-row"><div><b>✓</b><strong>Secure</strong><small>Your information is protected</small></div><div><b>➤</b><strong>Direct</strong><small>Forwarded to authority</small></div><div><b>◷</b><strong>Track</strong><small>Follow complaint progress</small></div></div></div>
<div class="form-card" id="complaint"><div class="form-head"><div class="icon">▤</div><div><h2>File a Complaint</h2><p>Submit your concern securely to the concerned authority.</p></div></div>@if($errors->any())<div class="alert">{{ $errors->first() }}</div>@endif<form action="{{ route('complaints.store') }}" method="POST" enctype="multipart/form-data">@csrf<div class="grid2"><label>Full Name *<input name="full_name" value="{{ old('full_name') }}" placeholder="Enter your full name" required></label><label>Mobile Number *<input name="mobile" value="{{ old('mobile') }}" placeholder="10 digit mobile number" required></label><label>Email <em>(Optional)</em><input type="email" name="email" value="{{ old('email') }}" placeholder="you@example.com"></label><label>Address *<input name="address" value="{{ old('address') }}" placeholder="Complete address" required></label><label>State *<input name="state" value="{{ old('state') }}" placeholder="State" required></label><label>District *<input name="district" value="{{ old('district') }}" placeholder="District" required></label></div><label>Subject *<input name="subject" value="{{ old('subject') }}" placeholder="Brief subject of complaint" required></label><label>Complaint Details *<textarea name="details" maxlength="10000" placeholder="Describe your complaint in detail..." required>{{ old('details') }}</textarea></label><label class="upload">Attach Files <em>(Optional, max 5 MB)</em><input type="file" name="attachment" accept=".jpg,.jpeg,.png,.pdf,.doc,.docx"></label><button class="submit" type="submit">➤ Submit Complaint</button><div class="secure">⌕ Your information is encrypted and sent securely.</div></form></div></section>
<section class="stats"><div><b>10,000+</b><span>Complaints Received</span></div><div><b>98%</b><span>Forwarded to Authorities</span></div><div><b>87%</b><span>Issues Resolved</span></div><div><b>24/7</b><span>Portal Access</span></div></section>
<section class="section" id="guidelines"><span class="eyebrow">SIMPLE PROCESS</span><h2>How It Works</h2><p class="muted">A straightforward four-step process from submission to resolution.</p><div class="steps"><article><i>01</i><h3>Fill the Form</h3><p>Enter your contact details and complaint information.</p></article><article><i>02</i><h3>Submit Complaint</h3><p>Submit after reviewing the information.</p></article><article><i>03</i><h3>Forwarded</h3><p>The complaint is automatically emailed to the configured authority.</p></article><article><i>04</i><h3>Confirmation</h3><p>Receive a reference number for future tracking.</p></article></div></section>
<section class="section categories"><span class="eyebrow">COMPLAINT CATEGORIES</span><h2>Common Areas for Complaints</h2><div class="category-grid"><div>🏛️<b>Public Services</b></div><div>🛣️<b>Infrastructure</b></div><div>🌿<b>Environment</b></div><div>❤<b>Health & Safety</b></div><div>🎓<b>Education</b></div><div>⚠<b>Corruption</b></div><div>⚡<b>Utilities</b></div><div>•••<b>Others</b></div></div></section>
<section class="cta"><div><span>BE PART OF A BETTER INDIA</span><h2>Your Complaint Can Make a Difference</h2><p>Together we can build a cleaner, safer and more transparent society.</p></div><a href="#complaint">File a Complaint Now →</a></section></main>
<footer><div><strong>Public Grievance Portal</strong><p>People's Voice · Accountable Governance · Better Service</p></div><div><b>Quick Links</b><a href="#home">Home</a><a href="#complaint">File a Complaint</a><a href="{{ route('complaints.track') }}">Track Complaint</a></div><div><b>Support</b><a href="#guidelines">Guidelines</a><a href="#faq">FAQs</a><a href="#">Privacy Policy</a></div></footer>
@endsection
